;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-indentation
        ess-smart-comma
        ess-yank
        handle-switch-frame
        keyboard-escape-quit
        kill-region
        previous-buffer
        ))

(setq mc/cmds-to-run-once
      '(
        ess-smart-S-assign
        indent-for-tab-command
        next-buffer
        overwrite-mode
        python-indent-electric-colon
        python-shell-send-buffer
        ))
